### ISSUE TITLE
Importing APM sample profile profile-pua_webtop_policy.conf.tar.gz [FAILED]

### ISSUE THREAD

**Issue by Mikej81** [billchurch/f5-pua#18]
Importing APM sample profile profile-pua_webtop_policy.conf.tar.gz [FAILED]

Previous command failed in /tmp/build_pua_offline.sh with error level: 255 on line: 495:

output=$((ng_import${policypathandfile}${apmpolicydisplayname})2>&1)

STDOUT/STDERR:
PHP Fatal error: Uncaught exception 'Exception' with message 'sourceMCPD::findUserUnknown user mode sourceMCPD::MODE_UNKNOWN' in /var/sam/www/admin/vpe2/private/php/include/accessPolicyContainer/dataSource.php:215 Stack trace: #0 /var/sam/www/admin/vpe2/private/php/include/accessPolicyContainer/dataSource.php(316): sourceMCPD::findUser() #1 /var/sam/www/admin/vpe2/private/php/include/accessPolicyContainer/dataSource.php(883): sourceMCPD::loadDll() #2 /var/sam/www/admin/vpe2/private/php/include/common.php(150): include_once('/var/sam/www/ad...') #3 /var/sam/www/admin/vpe2/private/php/include/common.php(139): modules::requireOnce('dataSource', 'accessPolicyCon...') #4 /usr/bin/ng_import(10): modules::load('dataSource') #5 {main} thrown in /var/sam/www/admin/vpe2/private/php/include/accessPolicyContainer/dataSource.php on line 215

Cleaning up...

**Comment by Mikej81** [comment]
Ah, makes sense.  Device is STIG'd, admin doesn't exist...

**Comment by Mikej81** [comment]
renabled admin and still:

Importing APM sample profile profile-pua_webtop_policy.conf.tar.gz [FAILED]



Previous command failed in /tmp/build_pua_offline.sh with error level: 255 on line: 495:

output=$((ng_import${policypathandfile}${apmpolicydisplayname})2>&1)


STDOUT/STDERR:
PHP Fatal error: Uncaught exception 'Exception' with message 'sourceMCPD::findUserUnknown user mode sourceMCPD::MODE_UNKNOWN' in /var/sam/www/admin/vpe2/private/php/include/accessPolicyContainer/dataSource.php:215 Stack trace: #0 /var/sam/www/admin/vpe2/private/php/include/accessPolicyContainer/dataSource.php(316): sourceMCPD::findUser() #1 /var/sam/www/admin/vpe2/private/php/include/accessPolicyContainer/dataSource.php(883): sourceMCPD::loadDll() #2 /var/sam/www/admin/vpe2/private/php/include/common.php(150): include_once('/var/sam/www/ad...') #3 /var/sam/www/admin/vpe2/private/php/include/common.php(139): modules::requireOnce('dataSource', 'accessPolicyCon...') #4 /usr/bin/ng_import(10): modules::load('dataSource') #5 {main} thrown in /var/sam/www/admin/vpe2/private/php/include/accessPolicyContainer/dataSource.php on line 215

Cleaning up...

**Comment by billchurch** [comment]
What version of BIG-IP?

**Comment by billchurch** [comment]
Turns out, package was downloaded incorrectly. Closing issue.
